version: '3.1'

services:
  
  apiWithKubernetesMongodb:
    container_name: apiWithKubernetesMongodb
    image: mongo
    ports:
      - "27018:27018"
    expose:
      - "27018"
    command: --bind_ip_all --port 27018
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongousradmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassadmin
      MONGO_INITDB_DATABASE: admin
    networks:
      - apinet

  apiWithKubernetes: 
    container_name: api_with_kubernetes
    image: sherryummen/api_with_kubernetes:v1
    hostname: api_with_kubernetes_mongodb
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
    - apinet
    volumes:
    - .:/go/src/api_with_kubernetes
    ports:
    - 8080:8080
    depends_on:
    - apiWithKubernetesMongodb
    links:
    - apiWithKubernetesMongodb
    labels:
      kompose.service.type: LoadBalancer

networks:
  apinet:
    driver: bridge